2021-10-18 17:17:12,481 INFO    MainThread:4624 [wandb_setup.py:_flush():69] setting env: {}
2021-10-18 17:17:12,481 INFO    MainThread:4624 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-18 17:17:12,481 INFO    MainThread:4624 [wandb_init.py:_log_setup():348] Logging user logs to C:\Users\Jack-Server\Documents\GitHub\PhD\Modern Implementations\DQN_etc\wandb\run-20211018_171712-q77sy9ht\logs\debug.log
2021-10-18 17:17:12,481 INFO    MainThread:4624 [wandb_init.py:_log_setup():349] Logging internal logs to C:\Users\Jack-Server\Documents\GitHub\PhD\Modern Implementations\DQN_etc\wandb\run-20211018_171712-q77sy9ht\logs\debug-internal.log
2021-10-18 17:17:12,481 INFO    MainThread:4624 [wandb_init.py:_jupyter_setup():300] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000163B15B09A0>
2021-10-18 17:17:12,481 INFO    MainThread:4624 [wandb_init.py:init():381] calling init triggers
2021-10-18 17:17:12,481 INFO    MainThread:4624 [wandb_init.py:init():386] wandb.init called with sweep_config: {}
config: {'env_name': 'CartPole-v0'}
2021-10-18 17:17:12,481 INFO    MainThread:4624 [wandb_init.py:init():430] starting backend
2021-10-18 17:17:12,481 INFO    MainThread:4624 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-10-18 17:17:12,481 INFO    MainThread:4624 [backend.py:ensure_launched():135] starting backend process...
2021-10-18 17:17:12,855 INFO    MainThread:4624 [backend.py:ensure_launched():139] started backend process with pid: 8660
2021-10-18 17:17:12,855 INFO    MainThread:4624 [wandb_init.py:init():435] backend started and connected
2021-10-18 17:17:12,918 INFO    MainThread:4624 [wandb_run.py:_label_probe_notebook():819] probe notebook
2021-10-18 17:17:12,918 INFO    MainThread:4624 [wandb_run.py:_label_probe_notebook():826] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-10-18 17:17:12,918 INFO    MainThread:4624 [wandb_init.py:init():494] updated telemetry
2021-10-18 17:17:12,934 INFO    MainThread:4624 [wandb_init.py:init():517] communicating current version
2021-10-18 17:17:14,512 INFO    MainThread:4624 [wandb_init.py:init():522] got version response upgrade_message: "wandb version 0.12.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-10-18 17:17:14,512 INFO    MainThread:4624 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-10-18 17:17:15,106 INFO    MainThread:4624 [wandb_init.py:init():557] starting run threads in backend
2021-10-18 17:17:20,119 INFO    MainThread:4624 [wandb_run.py:_console_start():1605] atexit reg
2021-10-18 17:17:20,119 INFO    MainThread:4624 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.WRAP
2021-10-18 17:17:20,119 INFO    MainThread:4624 [wandb_run.py:_redirect():1516] Wrapping output streams.
2021-10-18 17:17:20,135 INFO    MainThread:4624 [wandb_run.py:_redirect():1540] Redirects installed.
2021-10-18 17:17:20,135 INFO    MainThread:4624 [wandb_init.py:init():582] run started, returning control to user process
2021-10-18 17:17:32,515 INFO    MainThread:4624 [wandb_init.py:_pause_backend():262] pausing backend
2021-10-18 17:17:32,515 INFO    MainThread:4624 [jupyter.py:save_ipynb():301] looking for notebook: None
