1
1
Traceback (most recent call last):
  File "/home/elliot/Documents/GitHub/PhD/Modern Implementations/DQN_etc/DQN_Classes.py", line 274, in <module>
    train_h_DQN(env,meta_model,model,meta_replay_buffer,replay_buffer,
  File "/home/elliot/Documents/GitHub/PhD/Modern Implementations/DQN_etc/DQN_Classes.py", line 201, in train_h_DQN
    train_log(metric_name, episode_reward, frame_idx)
  File "/home/elliot/Documents/GitHub/PhD/Modern Implementations/DQN_etc/DQN_Classes.py", line 140, in train_log
    wandb.log({metric_name: metric_val}, global_step=frame_idx)
TypeError: log() got an unexpected keyword argument 'global_step'
Traceback (most recent call last):
  File "/home/elliot/Documents/GitHub/PhD/Modern Implementations/DQN_etc/DQN_Classes.py", line 274, in <module>
    train_h_DQN(env,meta_model,model,meta_replay_buffer,replay_buffer,
  File "/home/elliot/Documents/GitHub/PhD/Modern Implementations/DQN_etc/DQN_Classes.py", line 201, in train_h_DQN
    train_log(metric_name, episode_reward, frame_idx)
  File "/home/elliot/Documents/GitHub/PhD/Modern Implementations/DQN_etc/DQN_Classes.py", line 140, in train_log
    wandb.log({metric_name: metric_val}, global_step=frame_idx)
TypeError: log() got an unexpected keyword argument 'global_step'