Traceback (most recent call last):
  File "C:\Users\Jack-Server\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\dm_control\composer\define.py", line 37, in __get__
    return obj_dict[name]
KeyError: 'touch_force'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\Jack-Server\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\dm_control\composer\define.py", line 43, in __get__
    return obj_dict[name]
KeyError: 'touch_force'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\Jack-Server\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\IPython\core\interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-156c36a0ef10>", line 1, in <module>
    runfile('C:/Users/Jack-Server/Documents/GitHub/PhD/Modern Implementations/MuJoCo/Testing/C_L_RoboLoco_Learning.py', wdir='C:/Users/Jack-Server/Documents/GitHub/PhD/Modern Implementations/MuJoCo/Testing')
  File "C:\Users\Jack-Server\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\212.5080.64\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Users\Jack-Server\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\212.5080.64\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Jack-Server/Documents/GitHub/PhD/Modern Implementations/MuJoCo/Testing/C_L_RoboLoco_Learning.py", line 143, in <module>
    task = PressWithSpecificForce(roboloco)
  File "C:\Users\Jack-Server\Documents\GitHub\PhD\Modern Implementations\MuJoCo\Testing\C_L_RoboLoco_Task_Env.py", line 85, in __init__
    self._button = Button()
  File "C:\Users\Jack-Server\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\dm_control\composer\entity.py", line 219, in __init__
    self._observables = self._build_observables()
  File "C:\Users\Jack-Server\Documents\GitHub\PhD\Modern Implementations\MuJoCo\Testing\C_L_RoboLoco_Task_Env.py", line 29, in _build_observables
    return ButtonObservables(self)
  File "C:\Users\Jack-Server\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\dm_control\composer\entity.py", line 86, in __init__
    self._observables[attr_name] = getattr(self, attr_name)
  File "C:\Users\Jack-Server\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\dm_control\composer\define.py", line 46, in __get__
    return obj_dict.setdefault(name, self.fget(obj))
  File "C:\Users\Jack-Server\Documents\GitHub\PhD\Modern Implementations\MuJoCo\Testing\C_L_RoboLoco_Task_Env.py", line 65, in touch_force
    buffer_size=NUM_SUBSTEPS, aggregator='mean')
